broyden1 – SciFortran
broyden1 Subroutine
121 statements
Source File
public subroutine broyden1(ff, x, check, maxits, tol, tol1, tolmin, stpmx, noexit)
Arguments
Type Intent Optional Attributes Name
procedure(broydn_func) :: ff
real(kind=8), intent(inout), dimension(:) :: x
logical, optional :: check
integer, optional :: maxits
real(kind=8), optional :: tol
real(kind=8), optional :: tol1
real(kind=8), optional :: tolmin
real(kind=8), optional :: stpmx
logical, optional :: noexit
Calls
Contents
None
Call graph
broyden1 calls lower_triangle, put_diag, get_diag, lnsrch, qrupdt, vabs, outerprod, unit_matrix, qrdcmp, fdjac, rsolv
lower_triangle calls outerdiff
put_diag calls assert_eq2
get_diag calls assert_eq2
lnsrch calls vabs, assert_eq4
qrupdt calls ifirstloc, assert_eqn
qrdcmp calls vabs, outerprod, assert_eq4
fdjac calls assert_eq4
rsolv calls assert_eq4