c_tfft – SciFortran
c_tfft Subroutine
12 statements
Source File
public subroutine c_tfft(func_in, func_out)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), dimension(:) :: func_in
complex(kind=8), optional, dimension(size(func_in)) :: func_out
Calls
Called by
Source Code
  subroutine c_tfft(func_in,func_out)
    complex(8),dimension(:)                         :: func_in
    complex(8),dimension(size(func_in)),optional    :: func_out
    complex(8),dimension(size(func_in))             :: ftmp
    ftmp = ifftshift(func_in)
    call fft(ftmp)
    if(present(func_out))then
       func_out = fftshift(ftmp)*size(ftmp)
    else
       func_in  = fftshift(ftmp)*size(ftmp)
    endif
  end subroutine c_tfft
Call graph
c_tfft calls fftshift, fft, ifftshift
fftshift calls cfft_1d_shift, rfft_1d_shift
fft calls cfft_1d_forward, rfft_1d_forward
ifftshift calls cfft_1d_ishift, rfft_1d_ishift
cfft_1d_forward calls cfft1f, cfft1i
rfft_1d_forward calls rfft1f, rfft1i
tfft calls c_tfft