cauchy – SciFortran
cauchy Subroutine
198 statements
Source File
subroutine cauchy(n, x, l, u, nbd, g, iorder, iwhere, t, d, xcp, m, wy, ws, sy, wt, theta, col, head, p, c, wbp, v, nseg, iprint, sbgnrm, info, epsmch)
Arguments
Type Intent Optional Attributes Name
integer :: n
double precision :: x(n)
double precision :: l(n)
double precision :: u(n)
integer :: nbd(n)
double precision :: g(n)
integer :: iorder(n)
integer :: iwhere(n)
double precision :: t(n)
double precision :: d(n)
double precision :: xcp(n)
integer :: m
double precision :: wy(n,col)
double precision :: ws(n,col)
double precision :: sy(m,m)
double precision :: wt(m,m)
double precision :: theta
integer :: col
integer :: head
double precision :: p(2*m)
double precision :: c(2*m)
double precision :: wbp(2*m)
double precision :: v(2*m)
integer :: nseg
integer :: iprint
double precision :: sbgnrm
integer :: info
double precision :: epsmch
Calls
Called by
Contents
None
Call graph
cauchy calls hpsolb, dscal, daxpy, bmv, dcopy
bmv calls dtrsl
dtrsl calls daxpy
mainlb calls cauchy
setulb calls mainlb
bfgs_with_grad calls setulb
bfgs_no_grad calls setulb