cfft_1d_forward – SciFortran
cfft_1d_forward Subroutine
28 statements
Source File
public subroutine cfft_1d_forward(func)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(inout), dimension(:) :: func
Calls
Called by
Contents
Source Code
cfft_1d_forward
Source Code
  subroutine cfft_1d_forward(func)
    complex(8),dimension(:),intent(inout) :: func
    real(8),dimension(:),allocatable      :: wsave,work
    integer                               :: N,lenwrk,lensav,lenc,inc,ier
    N      = size(func)
    lenwrk = 2*N
    lensav = 2*N + int( log(dble(N))/log(2.d0) ) + 4
    lenc   = N
    inc    = 1
    allocate(wsave(lensav))
    allocate(work(lenwrk))
    call cfft1i(N,wsave,lensav,ier)
    if(ier==2)stop "cfft_1d_forward: LENSAV not big enough"
    call cfft1f(N,inc,func,lenc,wsave,lensav,work,lenwrk,ier)
    deallocate(wsave,work)
    select case(ier)
    case (0)
       return
    case (1)
       stop "cfft_1d_forward: LENC not big enough"
    case (2)
       stop "cfft_1d_forward: LENSAV not big enough"
    case (3)
       stop "cfft_1d_forward: LENWRK not big enough"
    case (20)
       stop "cfft_1d_forward: input error returned by lower level routine"
    end select
  end subroutine cfft_1d_forward
Call graph
cfft_1d_forward calls cfft1f, cfft1i
fft calls cfft_1d_forward
c_tfft calls fft
d_tfft calls fft
tfft calls c_tfft, d_tfft