CGFAM – SciFortran
CGFAM Subroutine
108 statements
Source File
subroutine CGFAM(N, X, F, G, D, GOLD, IPRINT, EPS, W, IFLAG, IREST, METHOD, FINISH, ITER, NFUN)
Arguments
Type Intent Optional Attributes Name
integer :: N
double precision :: X(N)
double precision :: F
double precision :: G(N)
double precision :: D(N)
double precision :: GOLD(N)
integer :: IPRINT(2)
double precision :: EPS
double precision :: W(N)
integer :: IFLAG
integer :: IREST
integer :: METHOD
logical :: FINISH
integer :: ITER
integer :: NFUN
Calls
Called by
Contents
Call graph
cgfam calls cgbd, cvsmod
cgbd calls 6, 2
cvsmod calls cstepm
fmin_cgplus_df calls cgfam
fmin_cgplus_f calls cgfam