ch12n – SciFortran
ch12n Subroutine
65 statements
Source File
public subroutine ch12n(n, z, nm, chf1, chd1, chf2, chd2)
************80
! CH12N computes Hankel functions of first and second kinds, complex argument.
Discussion:
Both the Hankel functions and their derivatives are computed.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
26 July 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, integer (kind = 4) N, the order of the functions.
Input, complex (kind = 8) Z, the argument.
Output, integer (kind = 4) NM, the highest order computed.
Output, complex (kind = 8) CHF1(0:n), CHD1(0:n), CHF2(0:n), CHD2(0:n),
the values of Hn(1)(z), Hn(1)'(z), Hn(2)(z), Hn(2)'(z).
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: n
complex(kind=8) :: z
integer(kind=4) :: nm
complex(kind=8) :: chf1(0:n)
complex(kind=8) :: chd1(0:n)
complex(kind=8) :: chf2(0:n)
complex(kind=8) :: chd2(0:n)
Calls
Contents
Call graph
ch12n calls ciknb, cjynb
ciknb calls msta1, msta2
cjynb calls msta1, msta2
msta1 calls envj
msta2 calls envj