csphik – SciFortran
csphik Subroutine
88 statements
Source File
public subroutine csphik(n, z, nm, csi, cdi, csk, cdk)
************80
! CSPHIK: complex modified spherical Bessel functions and derivatives.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
29 July 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, integer (kind = 4) N, the order of in(z) and kn(z).
Input, complex (kind = 8) Z, the argument.
Output, integer (kind = 4) NM, the highest order computed.
Output, complex (kind = 8) CSI(0:N), CDI(0:N), CSK(0:N), CDK(0:N),
the values of in(z), in'(z), kn(z), kn'(z).
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: n
complex(kind=8) :: z
integer(kind=4) :: nm
complex(kind=8) :: csi(0:n)
complex(kind=8) :: cdi(0:n)
complex(kind=8) :: csk(0:n)
complex(kind=8) :: cdk(0:n)
Calls
Contents
Call graph
csphik calls msta1, msta2
msta1 calls envj
msta2 calls envj