cv0 – SciFortran
cv0 Subroutine
125 statements
Source File
public subroutine cv0(kd, m, q, a0)
************80
! CV0 computes the initial characteristic value of Mathieu functions.
Discussion:
This procedure computes the initial characteristic value of Mathieu
functions for m <= 12 or q <= 300 or q <= m*m.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
03 August 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, integer (kind = 4) KD, the case code:
1, for cem(x,q)  (m = 0,2,4,...)
2, for cem(x,q)  (m = 1,3,5,...)
3, for sem(x,q)  (m = 1,3,5,...)
4, for sem(x,q)  (m = 2,4,6,...)
Input, integer (kind = 4) M, the order of the functions.
Input, real (kind = 8) Q, the parameter of the functions.
Output, real (kind = 8) A0, the characteristic value.
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: kd
integer(kind=4) :: m
real(kind=8) :: q
real(kind=8) :: a0
Calls
Called by
Contents
Call graph
cv0 calls cvql, cvqm
cva2 calls cv0
mtu0 calls cva2
mtu12 calls cva2