cva2 – SciFortran
cva2 Subroutine
86 statements
Source File
public subroutine cva2(kd, m, q, a)
************80
! CVA2 computes a specific characteristic value of Mathieu functions.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
22 July 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, integer (kind = 4) KD, the case code:
1, for cem(x,q)  (m = 0,2,4,...)
2, for cem(x,q)  (m = 1,3,5,...)
3, for sem(x,q)  (m = 1,3,5,...)
4, for sem(x,q)  (m = 2,4,6,...)
Input, integer (kind = 4) M, the order of the Mathieu functions.
Input, real (kind = 8) Q, the parameter of the Mathieu functions.
Output, real (kind = 8) A, the characteristic value.
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: kd
integer(kind=4) :: m
real(kind=8) :: q
real(kind=8) :: a
Calls
Called by
Contents
Call graph
cva2 calls cv0, cvql, cvqm, refine
cv0 calls cvql, cvqm
refine calls cvf
mtu0 calls cva2
mtu12 calls cva2