d_tfft – SciFortran
d_tfft Subroutine
12 statements
Source File
public subroutine d_tfft(func_in, func_out)
Arguments
Type Intent Optional Attributes Name
real(kind=8), dimension(:) :: func_in
real(kind=8), optional, dimension(size(func_in)) :: func_out
Calls
Called by
Contents
Source Code
d_tfft
Source Code
  subroutine d_tfft(func_in,func_out)
    real(8),dimension(:)                         :: func_in
    real(8),dimension(size(func_in)),optional    :: func_out
    complex(8),dimension(size(func_in))             :: ftmp
    ftmp = ifftshift(func_in)
    call fft(ftmp)
    if(present(func_out))then
       func_out = fftshift(ftmp)*size(ftmp)
    else
       func_in  = fftshift(ftmp)*size(ftmp)
    endif
  end subroutine d_tfft
Call graph
d_tfft calls ifftshift, fft, fftshift
ifftshift calls rfft_1d_ishift, cfft_1d_ishift
fft calls cfft_1d_forward, rfft_1d_forward
fftshift calls rfft_1d_shift, cfft_1d_shift
cfft_1d_forward calls cfft1i, cfft1f
rfft_1d_forward calls rfft1i, rfft1f
tfft calls d_tfft