daxpy – SciFortran
daxpy Subroutine
31 statements
Source File
subroutine daxpy(n, da, dx, incx, dy, incy)
Arguments
Type Intent Optional Attributes Name
integer :: n
double precision :: da
double precision :: dx(1)
integer :: incx
double precision :: dy(1)
integer :: incy
Called by
Contents
None
Call graph
orthnrm calls daxpy
dvdrvr calls daxpy, newvec
dtrsl calls daxpy
cauchy calls daxpy, bmv
newvec calls orthnrm
dvdson calls dvdrvr
mainlb calls cauchy, subsm, formk, cmprlb
subsm calls dtrsl
bmv calls dtrsl
formk calls dtrsl
dvdson_eigh_d calls dvdson
cmprlb calls bmv
setulb calls mainlb
bfgs_with_grad calls setulb
bfgs_no_grad calls setulb