dcopy – SciFortran
dcopy Subroutine
33 statements
Source File
subroutine dcopy(n, dx, incx, dy, incy)
Arguments
Type Intent Optional Attributes Name
integer :: n
double precision :: dx(1)
integer :: incx
double precision :: dy(1)
integer :: incy
Called by
Contents
None
Call graph
dvdson calls dcopy, dvdrvr
matupd calls dcopy
multbc calls dcopy
dvdrvr calls dcopy, multbc, newvec
mainlb calls dcopy, matupd, cauchy, formk, subsm, lnsrlb
orthnrm calls dcopy
cauchy calls dcopy
formk calls dcopy
subsm calls dcopy
lnsrlb calls dcopy
dvdson_eigh_d calls dvdson
setulb calls mainlb
newvec calls orthnrm
bfgs_with_grad calls setulb
bfgs_no_grad calls setulb