ddot – SciFortran
ddot Function
31 statements
Source File
function ddot(n, dx, incx, dy, incy)
Arguments
Type Intent Optional Attributes Name
integer :: n
double precision :: dx(1)
integer :: incx
double precision :: dy(1)
integer :: incy
Return Value doubleprecision
Called by
Contents
None
Call graph
addabs calls ddot
orthnrm calls ddot
dvdrvr calls ddot, addabs, newvec
setup calls addabs
newvec calls orthnrm
dvdson calls dvdrvr, setup
dvdson_eigh_d calls dvdson