difequ – SciFortran
difequ Subroutine
94 statements
Source File
subroutine difequ(mode, xx, v)
************80
! DIFEQU returns information about a differential equation.
Discussion:
This sample version of DIFEQU is for the example in chapter XV.  It is a
nonlinear second order two point boundary value problem.
Modified:
16 February 2007
Author:
Carl DeBoor
Reference:
Carl DeBoor,
A Practical Guide to Splines,
Springer, 2001,
ISBN: 0387953663,
LC: QA1.A647.v27.
Parameters:
Input, integer (kind = 4) MODE, an integer indicating the task to
be performed.
1, initialization
2, evaluate the differential equation at point XX.
3, specify the next side condition
4, analyze the approximation
Input, real (kind = 8) XX, a point at which information is wanted
Output, real (kind = 8) V, depends on the MODE.
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: mode
real(kind=8) :: xx
real(kind=8) :: v(20)
Called by
Contents
Common Blocks
approx other side
Common Blocks
common /approx/
Type Attributes Name Initial
real :: break(npiece)
real :: coef(ncoef)
integer(kind=4) :: l
integer(kind=4) :: kpm
common /other/
Type Attributes Name Initial
integer(kind=4) :: itermx
integer(kind=4) :: k
real :: rho(19)
common /side/
Type Attributes Name Initial
integer(kind=4) :: m
integer(kind=4) :: iside
real :: xside(10)
Call graph
colloc calls difequ, eqblok
putit calls difequ
eqblok calls putit