DINIT – SciFortran
DINIT Subroutine
20 statements
Source File
subroutine DINIT(N, A, X, INCX)
Arguments
Type Intent Optional Attributes Name
integer :: N
double precision :: A
double precision :: X(*)
integer :: INCX
Called by
Contents
None
Call graph
setup calls dinit
ovflow calls dinit
dvdson calls setup, dvdrvr
dvdrvr calls ovflow
dvdson_eigh_d calls dvdson