dscal – SciFortran
dscal Subroutine
26 statements
Source File
subroutine dscal(n, da, dx, incx)
Arguments
Type Intent Optional Attributes Name
integer :: n
double precision :: da
double precision :: dx(1)
integer :: incx
Called by
Contents
None
Call graph
addabs calls dscal
mainlb calls dscal, subsm, cauchy
dvdson calls dscal, dvdrvr, setup
subsm calls dscal
cauchy calls dscal
orthnrm calls dscal
newvec calls orthnrm
dvdrvr calls addabs, newvec
dvdson_eigh_d calls dvdson
setup calls addabs
setulb calls mainlb
bfgs_with_grad calls setulb
bfgs_no_grad calls setulb