dtrsl – SciFortran
dtrsl Subroutine
56 statements
Source File
subroutine dtrsl(t, ldt, n, b, job, info)
Arguments
Type Intent Optional Attributes Name
double precision :: t(ldt,*)
integer :: ldt
integer :: n
double precision :: b(*)
integer :: job
integer :: info
Calls
Called by
Contents
None
Call graph
dtrsl calls daxpy
bmv calls dtrsl
formk calls dtrsl
subsm calls dtrsl
cauchy calls bmv
mainlb calls formk, subsm, cauchy, cmprlb
cmprlb calls bmv
setulb calls mainlb
bfgs_with_grad calls setulb
bfgs_no_grad calls setulb