DVDRVR – SciFortran
DVDRVR Subroutine
69 statements
Source File
subroutine DVDRVR(OP, N, HIEND, LIM, MBLOCK, DIAG, NUME, NIV, NEIG, ISELEC, CRITE, CRITC, CRITR, ORTHO, MAXITER, EIGVAL, BASIS, AB, S, TEMPS, SVEC, SCRA1, ISCRA2, INCV, ICV, OLDVAL, NLOOPS, NMV, IERR)
Arguments
Type Intent Optional Attributes Name
real :: OP
integer :: N
logical :: HIEND
integer :: LIM
integer :: MBLOCK
real :: DIAG
integer :: NUME
integer :: NIV
integer :: NEIG
integer :: ISELEC
real :: CRITE
real :: CRITC
real :: CRITR
real :: ORTHO
integer :: MAXITER
real :: EIGVAL
real :: BASIS
real :: AB
real :: S
real :: TEMPS
real :: SVEC
real :: SCRA1
integer :: ISCRA2
integer :: INCV
integer :: ICV
real :: OLDVAL
integer :: NLOOPS
integer :: NMV
integer :: IERR
Calls
Called by
Contents
None
Call graph
dvdrvr calls ovflow, dspevx, ddot, newvec, dcopy, multbc, addabs, daxpy
ovflow calls dinit
newvec calls dnrm2, dgemv, orthnrm
multbc calls dcopy, dgemv
addabs calls ddot, dscal
orthnrm calls ddot, dcopy, daxpy, dscal
dvdson calls dvdrvr
dvdson_eigh_d calls dvdson