DVDSON – SciFortran
DVDSON Subroutine
85 statements
Source File
subroutine DVDSON(OP, N, LIM, DIAG, ILOW, IHIGH, ISELEC, NIV, MBLOCK, CRITE, CRITC, CRITR, ORTHO, MAXITER, WORK, IWRSZ, IWORK, IIWSZ, HIEND, NLOOPS, NMV, IERR)
Arguments
Type Intent Optional Attributes Name
real :: OP
integer :: N
integer :: LIM
real :: DIAG
integer :: ILOW
integer :: IHIGH
integer :: ISELEC
integer :: NIV
integer :: MBLOCK
real :: CRITE
real :: CRITC
real :: CRITR
real :: ORTHO
integer :: MAXITER
real :: WORK
integer :: IWRSZ
integer :: IWORK
integer :: IIWSZ
logical :: HIEND
integer :: NLOOPS
integer :: NMV
integer :: IERR
Calls
Called by
Contents
None
Call graph
dvdson calls dscal, setup, dvdrvr, dcopy
setup calls dinit, addabs
dvdrvr calls dcopy, newvec, ovflow, dspevx, ddot, addabs, multbc, daxpy
newvec calls dgemv, dnrm2, orthnrm
ovflow calls dinit
addabs calls dscal, ddot
multbc calls dcopy, dgemv
orthnrm calls dscal, dcopy, ddot, daxpy
dvdson_eigh_d calls dvdson