envj – SciFortran
envj Function
8 statements
Source File
function envj(n, x)
************80
! ENVJ is a utility function used by MSTA1 and MSTA2.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
14 March 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, integer (kind = 4) N, ?
Input, real (kind = 8) X, ?
Output, real (kind = 8) ENVJ, ?
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: n
real(kind=8) :: x
Return Value real(kind=8)
Called by
Contents
Source Code
envj
Source Code
function envj (n, x)
  !*****************************************************************************80
  !
  !! ENVJ is a utility function used by MSTA1 and MSTA2.
  !
  !  Licensing:
  !
  !    This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
  !    they give permission to incorporate this routine into a user program
  !    provided that the copyright is acknowledged.
  !
  !  Modified:
  !
  !    14 March 2012
  !
  !  Author:
  !
  !    Shanjie Zhang, Jianming Jin
  !
  !  Reference:
  !
  !    Shanjie Zhang, Jianming Jin,
  !    Computation of Special Functions,
  !    Wiley, 1996,
  !    ISBN: 0-471-11963-6,
  !    LC: QA351.C45.
  !
  !  Parameters:
  !
  !    Input, integer ( kind = 4 ) N, ?
  !
  !    Input, real ( kind = 8 ) X, ?
  !
  !    Output, real ( kind = 8 ) ENVJ, ?
  !
  implicit none
  real ( kind = 8 ) envj
  integer ( kind = 4 ) n
  real ( kind = 8 ) x
  envj = 0.5D+00 * log10 ( 6.28D+00 * n ) - n * log10 ( 1.36D+00 * x / n )
  return
end function envj
Call graph
msta1 calls envj
msta2 calls envj
lamv calls msta1, msta2
iknb calls msta1, msta2
jyv calls msta1, msta2
ciknb calls msta1, msta2
sphj calls msta1, msta2
cikvb calls msta1, msta2
csphjy calls msta1, msta2
jyna calls msta1, msta2
rctj calls msta1, msta2
csphik calls msta1, msta2
ikv calls msta1, msta2
cikna calls msta1, msta2
cjyva calls msta1, msta2
jynb calls msta1, msta2
lamn calls msta1, msta2
cjynb calls msta1, msta2
cikva calls msta1, msta2
cjyvb calls msta1, msta2
ikna calls msta1, msta2
cjyna calls msta1, msta2
sphi calls msta1, msta2
ch12n calls ciknb, cjynb
mtu12 calls jynb
rmn1 calls sphj
rmn2so calls rmn1
rswfp calls rmn1
rswfo calls rmn1, rmn2so