inverse_gammarnd – SciFortran
inverse_gammarnd Function
4 statements
Source File
function inverse_gammarnd(shape, scale) result(ans)
Arguments
Type Intent Optional Attributes Name
real(kind=8) :: shape
real(kind=8) :: scale
Return Value real(kind=8)
Calls
Contents
Source Code
inverse_gammarnd
Source Code
function inverse_gammarnd(shape,scale) result(ans)
  real(8) :: shape,scale,ans
  ! If X is gamma(shape, scale) then
  ! 1/Y is inverse gamma(shape, 1/scale)
  ans= 1d0/gammarnd(shape,1d0/scale)
end function inverse_gammarnd
Call graph
inverse_gammarnd calls gammarnd
gammarnd calls gammarnd, mersenne, normalrnd
normalrnd calls mersenne