ioread_control – SciFortran
ioread_control Subroutine
13 statements
Source File
subroutine ioread_control(pname, control)
Arguments
Type Intent Optional Attributes Name
character(len=*) :: pname
logical :: control
Called by
Contents
Source Code
ioread_control
Source Code
subroutine ioread_control(pname,control)
   character(len=*) :: pname
   logical          :: control
   !
   inquire(file=trim(pname),exist=control)
   if(.not.control)inquire(file=trim(pname)//".gz",exist=control)
   if(.not.control)then
      write(*,"(A)")"I can not read : +"//trim(pname)//" SKIP"
      call sleep(5)
      return
   else
      write(*,"(A,A)")"read:     "//trim(pname)
   endif
   !
end subroutine ioread_control
Call graph
data_reada4_r calls ioread_control
sreada4_rc calls ioread_control
sreada7_rc calls ioread_control
sreada1_rr calls ioread_control
data_reada5_c calls ioread_control
sreada2_rc calls ioread_control
data_reada3_r calls ioread_control
sreada4_rr calls ioread_control
sreada6_rc calls ioread_control
data_reada1_r calls ioread_control
data_reada4_c calls ioread_control
sreada5_rr calls ioread_control
data_reada2_r calls ioread_control
data_reada6_r calls ioread_control
data_reada7_r calls ioread_control
sreada1_rc calls ioread_control
sreada3_rr calls ioread_control
data_reada1_c calls ioread_control
data_reada3_c calls ioread_control
sreada7_rr calls ioread_control
data_reada5_r calls ioread_control
sreada2_rr calls ioread_control
sreada5_rc calls ioread_control
data_reada2_c calls ioread_control
data_reada6_c calls ioread_control
data_reada7_c calls ioread_control
sreada3_rc calls ioread_control
sreada6_rr calls ioread_control