lamv – SciFortran
lamv Subroutine
171 statements
Source File
public subroutine lamv(v, x, vm, vl, dl)
************80
! LAMV computes lambda functions and derivatives of arbitrary order.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
31 July 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, real (kind = 8) V, the order.
Input, real (kind = 8) X, the argument.
Output, real (kind = 8) VM, the highest order computed.
Output, real (kind = 8) VL(0:*), DL(0:*), the Lambda function and
derivative, of orders N+V0.
Arguments
Type Intent Optional Attributes Name
real(kind=8) :: v
real(kind=8) :: x
real(kind=8) :: vm
real(kind=8) :: vl(0:int(v))
real(kind=8) :: dl(0:int(v))
Calls
Contents
Call graph
lamv calls gam0, msta1, msta2
msta1 calls envj
msta2 calls envj