mainlb – SciFortran
mainlb Subroutine
328 statements
Source File
subroutine mainlb(n, m, x, l, u, nbd, f, g, factr, pgtol, ws, wy, sy, ss, wt, wn, snd, z, r, d, t, xp, wa, index, iwhere, indx2, task, iprint, csave, lsave, isave, dsave)
Arguments
Type Intent Optional Attributes Name
integer :: n
integer :: m
double precision :: x(n)
double precision :: l(n)
double precision :: u(n)
integer :: nbd(n)
double precision :: f
double precision :: g(n)
double precision :: factr
double precision :: pgtol
double precision :: ws(n,m)
double precision :: wy(n,m)
double precision :: sy(m,m)
double precision :: ss(m,m)
double precision :: wt(m,m)
double precision :: wn(2*m,2*m)
double precision :: snd(2*m,2*m)
double precision :: z(n)
double precision :: r(n)
double precision :: d(n)
double precision :: t(n)
double precision :: xp(n)
double precision :: wa(8*m)
integer :: index(n)
integer :: iwhere(n)
integer :: indx2(n)
character(len=60) :: task
integer :: iprint
character(len=60) :: csave
logical :: lsave(4)
integer :: isave(23)
double precision :: dsave(29)
Calls
Called by
Contents
None
Call graph
mainlb calls prn1lb, cmprlb, projgr, dcopy, errclb, prn2lb, timer, active, prn3lb, cauchy, freev, formk, subsm, lnsrlb, dscal, matupd, formt
cmprlb calls bmv
prn2lb calls 2
timer calls sngl
prn3lb calls 2
cauchy calls dcopy, dscal, hpsolb, daxpy, bmv
formk calls dcopy, dpofa, dtrsl
subsm calls dcopy, dscal, dtrsl
lnsrlb calls dcopy, dcsrch
matupd calls dcopy
formt calls dpofa
dtrsl calls daxpy
dcsrch calls dcstep
bmv calls dtrsl
setulb calls mainlb
bfgs_with_grad calls setulb
bfgs_no_grad calls setulb