msta1 – SciFortran
msta1 Function
32 statements
Source File
function msta1(x, mp)
************80
! MSTA1 determines a backward recurrence starting point for Jn(x).
Discussion:
This procedure determines the starting point for backward
recurrence such that the magnitude of
Jn(x) at that point is about 10^(-MP).
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
08 July 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, real (kind = 8) X, the argument.
Input, integer (kind = 4) MP, the negative logarithm of the
desired magnitude.
Output, integer (kind = 4) MSTA1, the starting point.
Arguments
Type Intent Optional Attributes Name
real(kind=8) :: x
integer(kind=4) :: mp
Return Value integer(kind=4)
Calls
Called by
Contents
Source Code
msta1
Source Code
function msta1 (x, mp)
  !*****************************************************************************80
  !
  !! MSTA1 determines a backward recurrence starting point for Jn(x).
  !
  !  Discussion:
  !
  !    This procedure determines the starting point for backward
  !    recurrence such that the magnitude of
  !    Jn(x) at that point is about 10^(-MP).
  !
  !  Licensing:
  !
  !    This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
  !    they give permission to incorporate this routine into a user program
  !    provided that the copyright is acknowledged.
  !
  !  Modified:
  !
  !    08 July 2012
  !
  !  Author:
  !
  !    Shanjie Zhang, Jianming Jin
  !
  !  Reference:
  !
  !    Shanjie Zhang, Jianming Jin,
  !    Computation of Special Functions,
  !    Wiley, 1996,
  !    ISBN: 0-471-11963-6,
  !    LC: QA351.C45.
  !
  !  Parameters:
  !
  !    Input, real ( kind = 8 ) X, the argument.
  !
  !    Input, integer ( kind = 4 ) MP, the negative logarithm of the
  !    desired magnitude.
  !
  !    Output, integer ( kind = 4 ) MSTA1, the starting point.
  !
  implicit none
  real ( kind = 8 ) a0
  ! real ( kind = 8 ) envj
  real ( kind = 8 ) f
  real ( kind = 8 ) f0
  real ( kind = 8 ) f1
  integer ( kind = 4 ) it
  integer ( kind = 4 ) mp
  integer ( kind = 4 ) msta1
  integer ( kind = 4 ) n0
  integer ( kind = 4 ) n1
  integer ( kind = 4 ) nn
  real ( kind = 8 ) x
  a0 = abs ( x )
  n0 = int ( 1.1D+00 * a0 ) + 1
  f0 = envj ( n0, a0 ) - mp
  n1 = n0 + 5
  f1 = envj ( n1, a0 ) - mp
  do it = 1, 20
     nn = n1 - ( n1 - n0 ) / ( 1.0D+00 - f0 / f1 )
     f = envj ( nn, a0 ) - mp
     if ( abs ( nn - n1 ) < 1 ) then
        exit
     end if
     n0 = n1
     f0 = f1
     n1 = nn
     f1 = f
  end do
  msta1 = nn
  return
end function msta1
Call graph
msta1 calls envj
cikna calls msta1
ciknb calls msta1
cikva calls msta1
cikvb calls msta1
cjyna calls msta1
cjynb calls msta1
cjyva calls msta1
cjyvb calls msta1
csphik calls msta1
csphjy calls msta1
ikna calls msta1
iknb calls msta1
ikv calls msta1
jyna calls msta1
jynb calls msta1
jyv calls msta1
lamn calls msta1
lamv calls msta1
rctj calls msta1
sphi calls msta1
sphj calls msta1
ch12n calls ciknb, cjynb
mtu12 calls jynb
rmn1 calls sphj
rmn2so calls rmn1
rswfo calls rmn1, rmn2so
rswfp calls rmn1