mtu0 – SciFortran
mtu0 Subroutine
75 statements
Source File
public subroutine mtu0(kf, m, q, x, csf, csd)
************80
! MTU0 computes Mathieu functions CEM(x,q) and SEM(x,q) and derivatives.
Licensing:
This routine is copyrighted by Shanjie Zhang and Jianming Jin.  However,
they give permission to incorporate this routine into a user program
provided that the copyright is acknowledged.
Modified:
20 July 2012
Author:
Shanjie Zhang, Jianming Jin
Reference:
Shanjie Zhang, Jianming Jin,
Computation of Special Functions,
Wiley, 1996,
ISBN: 0-471-11963-6,
LC: QA351.C45.
Parameters:
Input, integer (kind = 4) KF, the function code.
1 for computing cem(x,q) and cem'(x,q)
2 for computing sem(x,q) and sem'(x,q).
Input, integer (kind = 4) M, the order of the Mathieu functions.
Input, real (kind = 8) Q, the parameter of the Mathieu functions.
Input, real (kind = 8) X, the argument of the Mathieu functions,
in degrees.
Output, real (kind = 8) CSF, CSD, the values of cem(x,q) and cem'(x,q),
or of sem(x,q) and sem'(x,q).
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: kf
integer(kind=4) :: m
real(kind=8) :: q
real(kind=8) :: x
real(kind=8) :: csf
real(kind=8) :: csd
Calls
Contents
Call graph
mtu0 calls cva2, fcoef
cva2 calls cv0, cvql, cvqm, refine
cv0 calls cvql, cvqm
refine calls cvf