ORTHNRM – SciFortran
ORTHNRM Subroutine
45 statements
Source File
subroutine ORTHNRM(N, LIM, ORTHO, KPASS, NNCV, SCRA1, BASIS, RESTART)
Arguments
Type Intent Optional Attributes Name
integer :: N
integer :: LIM
real :: ORTHO
integer :: KPASS
integer :: NNCV
real :: SCRA1
real :: BASIS
logical :: RESTART
Calls
Called by
Contents
Call graph
orthnrm calls daxpy, dcopy, ddot, dscal
newvec calls orthnrm
dvdrvr calls newvec
dvdson calls dvdrvr
dvdson_eigh_d calls dvdson