pdf_var_1d – SciFortran
pdf_var_1d Function
6 statements
Source File
function pdf_var_1d(self) result(var)
Arguments
Type Intent Optional Attributes Name
type(pdf_kernel) :: self
Return Value real(kind=8)
Calls
Called by
Contents
Source Code
pdf_var_1d
Source Code
function pdf_var_1d(self) result(var)
  type(pdf_kernel) :: self
  real(8)          :: var,mean
  mean = pdf_mean_1d(self)
  var  = simps((self%x-mean)**2*self%pdf,self%xmin,self%xmax)
end function pdf_var_1d
Call graph
pdf_var_1d calls pdf_mean_1d, simps
pdf_mean_1d calls simps
pdf_sdev_1d calls pdf_var_1d
pdf_curt_1d calls pdf_var_1d
pdf_skew_1d calls pdf_sdev_1d
pdf_print_moments_pfile_1d calls pdf_sdev_1d, pdf_curt_1d, pdf_skew_1d