pdf_print_moments_pfile_1d – SciFortran
pdf_print_moments_pfile_1d Subroutine
9 statements
Source File
subroutine pdf_print_moments_pfile_1d(self, pfile)
Arguments
Type Intent Optional Attributes Name
type(pdf_kernel) :: self
character(len=*) :: pfile
Calls
Contents
Source Code
pdf_print_moments_pfile_1d
Source Code
subroutine pdf_print_moments_pfile_1d(self,pfile)
  type(pdf_kernel) :: self
  character(len=*) :: pfile
  integer          :: i,unit
  if(.not.self%status)stop "PDF_WRITE: PDF not allocated"
  open(free_unit(unit),file=trim(pfile))
  write(unit,*)pdf_mean_1d(self),pdf_sdev_1d(self),pdf_skew_1d(self),pdf_curt_1d(self)
  close(unit)
end subroutine pdf_print_moments_pfile_1d
Call graph
pdf_print_moments_pfile_1d calls free_unit, pdf_curt_1d, pdf_mean_1d, pdf_sdev_1d, pdf_skew_1d
pdf_curt_1d calls pdf_mean_1d, pdf_moment_1d, pdf_var_1d
pdf_mean_1d calls simps
pdf_sdev_1d calls pdf_var_1d
pdf_skew_1d calls pdf_mean_1d, pdf_sdev_1d, pdf_moment_1d
pdf_moment_1d calls simps
pdf_var_1d calls pdf_mean_1d, simps