pdf_mean_1d – SciFortran
pdf_mean_1d Function
5 statements
Source File
function pdf_mean_1d(self) result(mean)
Arguments
Type Intent Optional Attributes Name
type(pdf_kernel) :: self
Return Value real(kind=8)
Calls
Called by
Contents
Source Code
pdf_mean_1d
Source Code
function pdf_mean_1d(self) result(mean)
  type(pdf_kernel) :: self
  real(8)          :: mean
  mean = simps(self%x*self%pdf,self%xmin,self%xmax)
end function pdf_mean_1d
Call graph
pdf_mean_1d calls simps
pdf_var_1d calls pdf_mean_1d
pdf_print_moments_pfile_1d calls pdf_mean_1d, pdf_curt_1d, pdf_skew_1d, pdf_sdev_1d
pdf_curt_1d calls pdf_mean_1d, pdf_var_1d
pdf_skew_1d calls pdf_mean_1d, pdf_sdev_1d
pdf_sdev_1d calls pdf_var_1d