pdf_curt_1d – SciFortran
pdf_curt_1d Function
8 statements
Source File
function pdf_curt_1d(self) result(curt)
Arguments
Type Intent Optional Attributes Name
type(pdf_kernel) :: self
Return Value real(kind=8)
Calls
Called by
Contents
Source Code
pdf_curt_1d
Source Code
function pdf_curt_1d(self) result(curt)
  type(pdf_kernel) :: self
  real(8)          :: mean,var,curt
  mean = pdf_mean_1d(self)
  var  = pdf_var_1d(self)
  curt = pdf_moment_1d(self,4,mean)
  curt = curt/var**2
end function pdf_curt_1d
Call graph
pdf_curt_1d calls pdf_mean_1d, pdf_var_1d, pdf_moment_1d
pdf_mean_1d calls simps
pdf_var_1d calls pdf_mean_1d, simps
pdf_moment_1d calls simps
pdf_print_moments_pfile_1d calls pdf_curt_1d