random_chisq – SciFortran
random_chisq Function
7 statements
Source File
public function random_chisq(ndf, first) result(fn_val)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ndf
logical, intent(in) :: first
Return Value real
Calls
Contents
Call graph
random_chisq calls random_gamma
random_gamma calls random_gamma1, random_exponential, random_gamma2
random_gamma1 calls random_normal