setulb – SciFortran
setulb Subroutine
40 statements
Source File
subroutine setulb(n, m, x, l, u, nbd, f, g, factr, pgtol, wa, iwa, task, iprint, csave, lsave, isave, dsave)
Arguments
Type Intent Optional Attributes Name
integer :: n
integer :: m
double precision :: x(n)
double precision :: l(n)
double precision :: u(n)
integer :: nbd(n)
double precision :: f
double precision :: g(n)
double precision :: factr
double precision :: pgtol
double precision :: wa(2*m*n+5*n+11*m*m+8*m)
integer :: iwa(3*n)
character(len=60) :: task
integer :: iprint
character(len=60) :: csave
logical :: lsave(4)
integer :: isave(44)
double precision :: dsave(29)
Calls
Called by
Contents
None
Call graph
setulb calls mainlb
mainlb calls prn1lb, formk, projgr, active, cmprlb, lnsrlb, dscal, timer, prn3lb, errclb, dcopy, cauchy, freev, subsm, prn2lb, matupd, formt
formk calls dcopy, dtrsl, dpofa
cmprlb calls bmv
lnsrlb calls dcopy, dcsrch
timer calls sngl
prn3lb calls 2
cauchy calls dscal, dcopy, bmv, daxpy, hpsolb
subsm calls dscal, dcopy, dtrsl
prn2lb calls 2
matupd calls dcopy
formt calls dpofa
dcsrch calls dcstep
bmv calls dtrsl
dtrsl calls daxpy
bfgs_with_grad calls setulb
bfgs_no_grad calls setulb