SETUP – SciFortran
SETUP Subroutine
29 statements
Source File
subroutine SETUP(OP, N, LIM, NUME, HIEND, DIAG, MINELEM, BASIS, AB, S, NIV)
Arguments
Type Intent Optional Attributes Name
real :: OP
integer :: N
integer :: LIM
integer :: NUME
logical :: HIEND
real :: DIAG
double precision :: MINELEM
real :: BASIS
real :: AB
real :: S
integer :: NIV
Calls
Called by
Contents
Call graph
setup calls addabs, dinit
addabs calls ddot, dscal
dvdson calls setup
dvdson_eigh_d calls dvdson