StartMsg_MPI – SciFortran
StartMsg_MPI Subroutine
19 statements
Source File
public subroutine StartMsg_MPI(comm)
Arguments
Type Intent Optional Attributes Name
integer, optional :: comm
Calls
Called by
Contents
Source Code
StartMsg_MPI
Source Code
  subroutine StartMsg_MPI(comm)
    integer,optional :: comm
    integer          :: comm_,size
    integer          :: i
    comm_=MPI_COMM_WORLD;if(present(comm))comm_=comm
    if(comm_ /= Mpi_Comm_Null)then
       rank = Get_Rank_MPI(comm_)
       size = Get_Size_MPI(comm_)
       if(rank==0)write(*,'(a)')"---------------MPI----------------"
       do i=0,size-1
          call MPI_Barrier(comm_,ierr)
          if(rank==i)write(*,"(A,I6,A,I6,A)")"rank:",rank," of ",size," alive"
       enddo
       call MPI_Barrier(comm_,ierr)
       if(rank==0)write(*,'(a)')"----------------------------------"
       if(rank==0)write(*,'(a)')""
    endif
  end subroutine StartMsg_MPI
Call graph
startmsg_mpi calls mpi_barrier, get_rank_mpi, get_size_mpi
get_rank_mpi calls mpi_comm_rank, error_mpi
get_size_mpi calls mpi_comm_size, error_mpi
init_mpi calls startmsg_mpi