student_trnd – SciFortran
student_trnd Function
9 statements
Source File
function student_trnd(dof) result(ans)
Arguments
Type Intent Optional Attributes Name
real(kind=8) :: dof
Return Value real(kind=8)
Calls
Contents
Source Code
student_trnd
Source Code
function student_trnd(dof) result(ans)
  real(8) :: ans,dof,y1,y2
  if (dof <= 0.d0) then
     write(*,*) "STUDENT_TRND: Degrees of freedom must be positive"
  end if
  !
  ! ## See Seminumerical Algorithms by Knuth
  y1 = normalrnd(0d0,1d0)
  y2 = chi_squarernd(dof)
  ans= y1 / (y2 / dof)**0.5d0
  !
end function student_trnd
Call graph
student_trnd calls chi_squarernd, normalrnd
chi_squarernd calls gammarnd
normalrnd calls mersenne
gammarnd calls normalrnd, mersenne, gammarnd