vabs – SciFortran
vabs Function
5 statements
Source File
public function vabs(v)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in), dimension(:) :: v
Return Value real(kind=8)
Called by
Contents
Source Code
vabs
Source Code
  function vabs(v)
    real(8), dimension(:), intent(in) :: v
    real(8) :: vabs
    vabs=sqrt(dot_product(v,v))
  end function vabs
Call graph
broyden1 calls vabs, lnsrch, qrdcmp
lnsrch calls vabs
qrdcmp calls vabs