fft – SciFortran
fft Interface
3 statements
Source File
public interface fft
Calls
Called by
Contents
Module Procedures
rfft_1d_forward cfft_1d_forward
Module Procedures
public subroutine rfft_1d_forward(func)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(inout), dimension(:) :: func
public subroutine cfft_1d_forward(func)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(inout), dimension(:) :: func
Call graph
fft calls cfft_1d_forward, rfft_1d_forward
cfft_1d_forward calls cfft1f, cfft1i
rfft_1d_forward calls rfft1f, rfft1i
c_tfft calls fft
d_tfft calls fft
tfft calls c_tfft, d_tfft