ifftn – SciFortran
ifftn Interface
3 statements
Source File
public interface ifftn
Calls
Contents
Module Procedures
rfft_nd_backward cfft_nd_backward
Module Procedures
public subroutine rfft_nd_backward(func, N, lot)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(inout), dimension(:) :: func
integer, intent(in) :: N
integer, intent(in) :: lot
public subroutine cfft_nd_backward(func, n, lot)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), intent(inout), dimension(:) :: func
integer, intent(in) :: n
integer, intent(in) :: lot
Call graph
ifftn calls cfft_nd_backward, rfft_nd_backward
cfft_nd_backward calls cfftmb, cfftmi
rfft_nd_backward calls rfftmb, rfftmi