itfft – SciFortran
itfft Interface
3 statements
Source File
public interface itfft
Calls
Contents
Module Procedures
d_itfft c_itfft
Module Procedures
public subroutine d_itfft(func_in, func_out)
Arguments
Type Intent Optional Attributes Name
real(kind=8), dimension(:) :: func_in
real(kind=8), optional, dimension(size(func_in)) :: func_out
public subroutine c_itfft(func_in, func_out)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), dimension(:) :: func_in
complex(kind=8), optional, dimension(size(func_in)) :: func_out
Call graph
itfft calls c_itfft, d_itfft
c_itfft calls fftex, ifft, ifftshift
d_itfft calls fftex, ifft, ifftshift
fftex calls cfft_1d_ex, rfft_1d_ex
ifft calls cfft_1d_backward, rfft_1d_backward
ifftshift calls cfft_1d_ishift, rfft_1d_ishift
cfft_1d_backward calls cfft1b, cfft1i
rfft_1d_backward calls rfft1b, rfft1i