reg – SciFortran
reg Interface
3 statements
Source File
public interface reg
Called by
Contents
Module Procedures
reg_filename
Module Procedures
private function reg_filename(file) result(reg)
Arguments
Type Intent Optional Attributes Name
character(len=*) :: file
Return Value character(len=len_trim)
Call graph
file_gunzip calls reg
file_untargz calls reg
file_length calls reg, file_gunzip
file_info calls reg
file_size calls reg
file_gzip calls reg, file_size