tfft – SciFortran
tfft Interface
3 statements
Source File
public interface tfft
Calls
Contents
Module Procedures
d_tfft c_tfft
Module Procedures
public subroutine d_tfft(func_in, func_out)
Arguments
Type Intent Optional Attributes Name
real(kind=8), dimension(:) :: func_in
real(kind=8), optional, dimension(size(func_in)) :: func_out
public subroutine c_tfft(func_in, func_out)
Arguments
Type Intent Optional Attributes Name
complex(kind=8), dimension(:) :: func_in
complex(kind=8), optional, dimension(size(func_in)) :: func_out
Call graph
tfft calls d_tfft, c_tfft
d_tfft calls ifftshift, fft, fftshift
c_tfft calls ifftshift, fft, fftshift
ifftshift calls cfft_1d_ishift, rfft_1d_ishift
fft calls rfft_1d_forward, cfft_1d_forward
fftshift calls cfft_1d_shift, rfft_1d_shift
rfft_1d_forward calls rfft1i, rfft1f
cfft_1d_forward calls cfft1i, cfft1f