name: API docs generation via FORD
on:
  workflow_dispatch: # manual-run
  push: 
    branches:
      - master # foreach push on master
jobs:
  CD:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9] # Version of Python we want to use.

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: FORD setup
      uses: QcmPlab/DocSetup@master
      with:
        python-version: ${{ matrix.python-version }}

    - name: Deploy DOCS
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: doc      # The folder the action should deploy.